# Logstash Configuration
# Module 6 - Le√ßon 6.5 : Logging & Monitoring avec ELK

http.host: "0.0.0.0"
xpack.monitoring.enabled: false
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]

# Pipeline configuration
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Logging
log.level: info
path.logs: /var/log/logstash
